### PR TITLE
print test

### PR DESCRIPTION
**Pull request by alphide**
bruh

### CODE REVIEW

**Review by rickychu — COMMENTED** [review]
No, that's not what I asked for

**Comment by rickychu** [comment]
/**
	 * Prints the array of piles of cards
	 * @param array array of cards
	 */
	public static void printPiles(ArrayList<Integer> array)
	{
// Add your print statement here
		System.out.println(array.toString());
	}

**Comment by alphide** [comment]
what does that mean

**Comment by alphide** [comment]
give me clearer directions....

**Pull request merged**
